export const welcomeMessage = [
  'Welcome! 👋',
  '',
  'Here is how to use this bot:',
  '',
  '1) Add a Google Sheet: /add_sheet',
  '   • Create a Google Sheet and share it with the service account (you will see the email during the flow).',
  '   • Send the Sheet URL and give it a name.',
  '',
  '2) Select your active sheet: /select_sheet',
  '   • The active sheet will be used for all actions below.',
  '',
  '3) Add a spending: /add_spending',
  '   • You will be asked for an amount and a description.',
  '   • Note: you must have an active sheet selected.',
  '',
  '4) Invite others to your sheet: /share_sheet',
  '   • Get a personal link that others can use to join your active sheet.',
  '',
  'Open the main menu anytime: /menu',
  'Cancel any ongoing flow: /cancel',
].join('\n');
